### ISSUE TITLE
Does not compile on Ubuntu 16.04 / Postgres 9.6.3

### ISSUE THREAD

**Issue by vmihailenco** [cybertec-postgresql/pg_squeeze#3]
```
PG_CONFIG=/usr/bin/pg_config make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic -I. -I./ -I/usr/include/postgresql/9.6/server -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o pg_squeeze.o pg_squeeze.c
pg_squeeze.c: In function ‘setup_decoding’:
pg_squeeze.c:895:10: warning: passing argument 3 of ‘CreateInitDecodingContext’ makes integer from pointer without a cast [-Wint-conversion]
          logical_read_local_xlog_page,
          ^
In file included from pg_squeeze.h:23:0,
                 from pg_squeeze.c:10:
/usr/include/postgresql/9.6/server/replication/logical.h:80:32: note: expected ‘bool {aka char}’ but argument is of type ‘int (*)(XLogReaderState *, XLogRecPtr,  int,  XLogRecPtr,  char *, TimeLineID *) {aka int (*)(struct XLogReaderState *, long unsigned int,  int,  long unsigned int,  char *, unsigned int *)}’
 extern LogicalDecodingContext *CreateInitDecodingContext(char *plugin,
                                ^
pg_squeeze.c:894:8: error: too few arguments to function ‘CreateInitDecodingContext’
  ctx = CreateInitDecodingContext(REPL_PLUGIN_NAME, NIL,
        ^
In file included from pg_squeeze.h:23:0,
                 from pg_squeeze.c:10:
/usr/include/postgresql/9.6/server/replication/logical.h:80:32: note: declared here
 extern LogicalDecodingContext *CreateInitDecodingContext(char *plugin,
                                ^
<builtin>: recipe for target 'pg_squeeze.o' failed
make: *** [pg_squeeze.o] Error 1
```

Relevant link - http://www.postgresql-archive.org/pgsql-Don-t-use-on-disk-snapshots-for-exported-logical-decoding-snapsh-td5958816.html

**Comment by vmihailenco** [comment]
Gentle ping. The fix looks trivial, but I am not 100% sure if pg_squeeze requires full snapshot or not...

**Comment by ahouska** [comment]
Fixed.
